# ---------------------------------------------------------------------------
# Locates SFML 2.6 - and refuses SFML 3, even when both are installed.
#
# SFML 3 is *not* source-compatible with SFML 2: sf::Event became a
# variant (no `.type`, no `.key`), sf::Rect swapped left/top/width/height
# for position/size vectors, sf::Text and sf::Sound take their resource
# in the constructor, Font::loadFromFile became openFromFile,
# setPosition takes a Vector2f, pollEvent returns std::optional, and
# Mouse::XButton1 became Extra1.
#
# The trap this file exists to close: `find_package(SFML 2.6 ...)` means
# "2.6 **or newer**", so on a machine with both versions installed CMake
# happily hands back SFML 3, the project configures without a word, and
# the first sign of trouble is a hundred compiler errors inside the
# engine's backend. A version range would be the tidy answer, but
# SFML 2.6.1 ships a version file generated by an older CMake that does
# not understand ranges, so CMake silently falls back to the lower bound
# and picks 3.x anyway. Hence the explicit check below.
#
# Search order:
#   1. -DSFML_DIR=<prefix>/lib/cmake/SFML  (or -DSFML_ROOT=<prefix>)
#   2. a vendored build under external/SFML-2.6.1
#   3. any installed SFML whose version starts with 2.
#   4. failing all of those, SFML 2.6.1 is fetched and built from source
#      (-DBOMBERMAN_FETCH_SFML=OFF turns this off).
# ---------------------------------------------------------------------------

option(BOMBERMAN_FETCH_SFML "Build SFML 2.6.1 from source when no SFML 2.x is available" ON)

set(BOMBERMAN_SFML_COMPONENTS graphics window system audio)

# ---------------------------------------------------------------------------
# Reads the version out of an SFMLConfigVersion.cmake without running it.
# ---------------------------------------------------------------------------
function(bomberman_sfml_config_version config_dir out_version)
    set(${out_version} "" PARENT_SCOPE)

    set(version_file "${config_dir}/SFMLConfigVersion.cmake")
    if(NOT EXISTS "${version_file}")
        return()
    endif()

    file(READ "${version_file}" contents)
    # Both the CMake-generated and the hand-written variants spell it
    # `set(PACKAGE_VERSION "2.6.1")`.
    string(REGEX MATCH "set\\(PACKAGE_VERSION[ \t]+\"?([0-9]+\\.[0-9]+(\\.[0-9]+)?)\"?" _m "${contents}")
    if(CMAKE_MATCH_1)
        set(${out_version} "${CMAKE_MATCH_1}" PARENT_SCOPE)
    endif()
endfunction()

# ---------------------------------------------------------------------------
# Collects every SFML config directory on this machine and keeps the 2.x one.
# ---------------------------------------------------------------------------
function(bomberman_find_sfml2_dir out_dir out_rejected)
    set(candidates "")

    # Explicit user prefixes first.
    foreach(root IN LISTS SFML_ROOT SFML_VENDORED_ROOT)
        if(root)
            list(APPEND candidates "${root}/lib/cmake/SFML" "${root}/lib64/cmake/SFML")
        endif()
    endforeach()
    if(DEFINED ENV{SFML_ROOT})
        list(APPEND candidates "$ENV{SFML_ROOT}/lib/cmake/SFML")
    endif()

    # Then the usual places a self-built SFML 2.6 ends up in, and the
    # distribution's own location.
    file(GLOB system_candidates
            "/usr/local/lib/cmake/SFML"
            "/usr/local/lib/*/cmake/SFML"
            "/opt/SFML*/lib/cmake/SFML"
            "$ENV{HOME}/SFML*/lib/cmake/SFML"
            "/usr/lib/cmake/SFML"
            "/usr/lib/*/cmake/SFML"
    )
    list(APPEND candidates ${system_candidates})
    list(REMOVE_DUPLICATES candidates)

    set(rejected "")
    foreach(dir IN LISTS candidates)
        if(NOT EXISTS "${dir}/SFMLConfig.cmake")
            continue()
        endif()

        bomberman_sfml_config_version("${dir}" version)
        if(version MATCHES "^2\\.")
            message(STATUS "SFML: selected ${version} at ${dir}")
            set(${out_dir} "${dir}" PARENT_SCOPE)
            set(${out_rejected} "${rejected}" PARENT_SCOPE)
            return()
        endif()

        if(version)
            list(APPEND rejected "${version} (${dir})")
        endif()
    endforeach()

    set(${out_dir} "" PARENT_SCOPE)
    set(${out_rejected} "${rejected}" PARENT_SCOPE)
endfunction()

# ---- Vendored prefix, if the repository carries one ------------------------

set(SFML_VENDORED_ROOT "${CMAKE_SOURCE_DIR}/external/SFML-2.6.1")
if(WIN32)
    set(SFML_VENDORED_ROOT "${SFML_VENDORED_ROOT}/windows")
elseif(UNIX)
    set(SFML_VENDORED_ROOT "${SFML_VENDORED_ROOT}/linux")
endif()

# ---- 1-3. An explicit SFML_DIR wins; otherwise pick a 2.x install ----------

if(SFML_DIR)
    bomberman_sfml_config_version("${SFML_DIR}" _explicit_version)
    if(_explicit_version AND NOT _explicit_version MATCHES "^2\\.")
        message(FATAL_ERROR
                "SFML_DIR points at SFML ${_explicit_version}, but this project needs the "
                "2.6.x API (the assignment's reference platform is SFML 2.6.1).")
    endif()
    message(STATUS "SFML: using the explicitly provided ${SFML_DIR}")
else()
    bomberman_find_sfml2_dir(_sfml2_dir _rejected_versions)
    if(_sfml2_dir)
        # Setting SFML_DIR is what pins the choice: without it,
        # find_package is free to prefer a newer copy from another prefix.
        set(SFML_DIR "${_sfml2_dir}" CACHE PATH "Directory containing SFMLConfig.cmake" FORCE)
    elseif(_rejected_versions)
        message(STATUS "SFML: ignoring incompatible installation(s): ${_rejected_versions}")
    endif()
endif()

if(SFML_DIR)
    find_package(SFML 2.6 COMPONENTS ${BOMBERMAN_SFML_COMPONENTS} QUIET)
endif()

# Belt and braces: whatever path got us here, refuse to continue with a
# version whose API we do not speak.
if(SFML_FOUND AND DEFINED SFML_VERSION_MAJOR AND NOT SFML_VERSION_MAJOR EQUAL 2)
    message(STATUS "SFML: discarding version ${SFML_VERSION}, the 2.x API is required")
    unset(SFML_FOUND)
    unset(SFML_DIR CACHE)
endif()

if(SFML_FOUND)
    return()
endif()

# ---- 4. Build 2.6.1 from source -------------------------------------------

if(NOT BOMBERMAN_FETCH_SFML)
    message(FATAL_ERROR
            "No SFML 2.6.x found.\n"
            "Point the build at one explicitly:\n"
            "    cmake -S . -B build -DSFML_DIR=/path/to/SFML-2.6.1/lib/cmake/SFML\n"
            "or install it (Ubuntu 24.04: sudo apt install libsfml-dev), or re-run with "
            "-DBOMBERMAN_FETCH_SFML=ON to have it built from source.")
endif()

message(STATUS "SFML: no 2.6.x installation found - fetching and building SFML 2.6.1 (first configure only)")

include(FetchContent)

# If one of SFML's own dependencies is missing, the failure appears
# halfway through *its* configure step, which is not an obvious place to
# look - so the requirements are stated up front.
if(UNIX AND NOT APPLE)
    message(STATUS
            "SFML: building from source needs the X11/OpenGL/audio development headers. "
            "On Debian/Ubuntu: sudo apt install libxrandr-dev libxcursor-dev libxi-dev "
            "libudev-dev libgl1-mesa-dev libfreetype-dev libopenal-dev libflac-dev "
            "libvorbis-dev")
endif()

set(SFML_BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
set(SFML_BUILD_DOC OFF CACHE BOOL "" FORCE)
set(SFML_BUILD_NETWORK OFF CACHE BOOL "" FORCE)
# Static, so the resulting binary does not need this copy of SFML on the
# library path at run time - which is most of the point of building it.
set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)

FetchContent_Declare(
        SFML
        GIT_REPOSITORY https://github.com/SFML/SFML.git
        GIT_TAG 2.6.1
        GIT_SHALLOW TRUE
)
FetchContent_MakeAvailable(SFML)

# The targets are called sfml-graphics/window/system/audio whether SFML
# was found or built here, so nothing downstream knows the difference.
